baseurl: "/"
title: "Ashli Taylor"
page_load_js: "assets/js/main.js"
params:
  layout_style: overflow
  palette: blue
  header:
    title: "Ashli Taylor"
    tagline: Data Scientist
    profile_img: images/avatar.png
    bg: dark
    has_nav: true
    has_social: true
  footer:
    content: "&copy; 2019 Ashli Taylor. All rights reserved. Designed with &hearts; on"
    
    links:
      - text: "Jekyll"
        url: https://jekyllrb.com/
        new_window: true
sass:
  input_file: sass/main.scss.njk
  output_file: assets/css/main.css
  indentWidth: 4
  outputStyle: nested
  precision: 10
